[package]
name = "inquire"
version = "0.0.7-alpha.0"
license = "MIT"
edition = "2018"

description = "inquire is a library for building interactive prompts on terminals"
repository = "https://github.com/mikaelmello/inquire"
homepage = "https://github.com/mikaelmello/inquire"
authors = ["Mikael Mello <git@mikaelmello.com>"]
keywords = ["cli", "ask", "prompt", "question", "interactive"]
categories = ["command-line-interface", "value-formatting"]
exclude = ["/.github", "/.vscode", "/.idea", "/assets", "/release.sh"]

[features]
default = ["builtin_validators"]
builtin_validators = []
date = ["chrono"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
crossterm = "0.20"
unicode-segmentation = "1"
chrono = {version = "0.4",  optional = true }
thiserror = "1"
bitflags = "1.0"

[dev-dependencies]
ntest = "0.7.3"

[[example]]
name = "form"
required-features = ["date"]

[[example]]
name = "date"
required-features = ["date"]

[[example]]
name = "expense_tracker"
required-features = ["date"]

[[example]]
name = "date_complete"
required-features = ["date"]
