[package]
name = "inquire"
version = "0.0.1"
license = "MIT"
edition = "2018"

description = "inquire is a library for building interactive prompts on terminals"
repository = "https://github.com/mikaelmello/inquire"
homepage = "https://github.com/mikaelmello/inquire"
authors = ["Mikael Mello <git@mikaelmello.com>"]
keywords = ["cli", "ask", "prompt", "question", "interactive"]
categories = ["command-line-interface", "value-formatting"]

[dependencies]
termion = "1"
unicode-segmentation = "1"
simple-error = "0.2.3"
regex = "1"
lazy_static = "1.4.0"