allow-branch = ["main"]
sign-commit = true
sign-tag = true
enable-all-features = true
consolidate-pushes = true

pre-release-commit-message = "chore: release v{{version}}"
post-release-commit-message = "chore: start next development iteration v{{next_version}}"

pre-release-replacements = [
  {file="README.md", search="inquire = \".*\"", replace="{{crate_name}} = \"{{version}}\""},
  {file="README.md", search="inquire = \\{ version = \"[\\.0-9]*\"", replace="{{crate_name}} = { version = \"{{version}}\""},

  {file="CRATE_README.md", search="inquire = \".*\"", replace="{{crate_name}} = \"{{version}}\""},
  {file="CRATE_README.md", search="inquire = \\{ version = \"[\\.0-9]*\"", replace="{{crate_name}} = { version = \"{{version}}\""},

  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="<!-- ReleaseDate -->", replace="- {{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] <!-- ReleaseDate -->\n\n- No changes since the latest release below.\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/mikaelmello/inquire/compare/{{tag_name}}...HEAD", exactly=1},
]
