name: build
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --verbose --all-features
      - name: Test with no features [crossterm]
        run: cargo test --verbose --no-default-features --features=crossterm
      - name: Test with no features [termion]
        if: matrix.os != 'windows-latest'
        run: cargo test --verbose --no-default-features --features=termion
      - name: Test with default features
        run: cargo test --verbose
      - name: Test with all features
        run: cargo test --verbose --all-features
