name: build
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [win-gnu, win-msvc, msrv]
        include:
          - build: win-gnu
            os: windows-latest
            rust: stable-x86_64-gnu

          - build: win-msvc
            os: windows-latest
            rust: stable

          - build: msrv
            os: windows-latest
            rust: 1.53.0

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Build with default features
        run: cargo build --verbose
      - name: Test with no features [crossterm]
        run: cargo test --verbose --no-default-features --features=crossterm
      - name: Test with default features
        run: cargo test --verbose
      - name: Test with all supported features
        run: cargo test --verbose --no-default-features --features=crossterm,date,builtin_validators
